name: Trigger API

on:
  workflow_dispatch:

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API
        run: |
          curl -X POST "https://gg-dework-admin.netlify.app/.netlify/functions/updateDatabase" 
