name: Trigger API

on:
  push: # Triggers the workflow on push events
    branches:
      - main # Replace with your default branch name

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API
        run: |
          curl -X POST "https://your-netlify-site-url/.netlify/functions/updateDatabase"
