name: Trigger GG Internal API

on:
  workflow_dispatch:
  schedule:
  # 22h00 UTC Tue and Sat – https://crontab.guru
  - cron: 0 12 * * 6,2

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API
        run: |
          curl -X POST ${{ secrets.UPDATE_GG_INTERNAL_OP}} 
