name: Trigger Comm Lead Gen API

on:
  workflow_dispatch:
  schedule:
  # 22h00 UTC Tue and Sat – https://crontab.guru
  - cron: 5 12 * * 6,2

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API
        run: |
          curl -X POST ${{ secrets.UPDATE_COMM_LEAD_GEN }} 
